version: "3.8"

services:
  redis-master:
    container_name: redis-master
    image: redis:6.2.5
    ports: 
      - 6379:6379
    command: redis-server /redis/redis.conf
    volumes:
      - ./:/redis
      - ./data:/redis/data

  redis-slave:
    # container_name: redis-slave
    # image: redis:6.2.5
    # command: redis-server /redis/slave.conf
    # volumes:
    #   - ./:/redis
    build:
      context: ./slave-image
    environment:
      - SLAVE_IP_MASTER=redis-master
      - SLAVE_LOG_FILE=""
    links: 
      - redis-master
    volumes:
      - ./data:/redis/data
  
  redis-sentinel:
    # container_name: redis-sentinel
    environment: 
      - SENTINEL_IP_MASTER=redis-master
      - SENTINEL_LOG_FILE=""
    build: 
      context: ./sentinel-image
    links:
      - redis-master
    volumes:
      - ./data:/redis/data
